apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: auth
  template: 
    metadata: 
      labels: 
        app: auth
    spec: 
      containers:
        - name: auth
          image: everorman/auth
          env: 
            - name: JWT_KEY # this name made reference to the var inside of our pod
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # Secret name, you can see the name with kubectl get secrets 
                  key: JWT_KEY # Key pair inside of the secret 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec: 
  selector: 
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
  
    